---
###############################################################################
# Repair
###############################################################################
# DB repair script is deployed successfully.
#
# Tests:
# * DBRepair.sh script is installed to /usr/bin/DBRepair.sh with correct
#   permissions.
# * Repair job and systemd timers are set.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    host_vars:
      plex-debian-13-repair:
        plex_srv_repair_enable: true
platforms:
  - name: 'plex-debian-13-repair'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'converge'
    - 'verify'
    - 'destroy'
