---
###############################################################################
# Plex Auto Update Service
###############################################################################
# Execute auto-update script to configure entitlements if configured. Set
# custom plex auto-update service to check and install new plex releases when
# enabled. Deferrable.
#
# Reference:
# * https://github.com/mrworf/plexupdate
# * https://github.com/linuxserver/docker-plex/blob/master/root/etc/

- name: 'Auto update | 🗘 processing entitlements (~4 minutes) 🗘'
  when: plex_flg_auto_update
  ansible.builtin.debug:
    msg: 'Processing entitlements (~4 minutes).'

- name: 'Auto update | cmd | process entitlements'
  when: plex_flg_auto_update
  ansible.builtin.shell: '{{ plex___update._dest_file }}'
  args:
    executable: '/bin/bash'
  changed_when: false

- name: 'Auto update | filesystem | set /etc/systemd/system/plex_update.*'
  when: plex_flg_auto_update
  notify: 'Handlers | enable plex_update'
  ansible.builtin.template:
    src: '{{ "systemd/" ~ item ~ ".j2" }}'
    dest: '{{ "/etc/systemd/system/" ~ item }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - 'plex_update.service'
    - 'plex_update.timer'

- name: 'Auto update | filesystem | remove /etc/systemd/system/plex_update.*'
  when: not plex_flg_auto_update
  notify: 'Handlers | disable plex_update'
  ansible.builtin.file:
    path: '{{ "/etc/systemd/system/" ~ item }}'
    state: 'absent'
  loop:
    - 'plex_update.service'
    - 'plex_update.timer'
