---
###############################################################################
# Backup
###############################################################################

- name: 'Backup | systemd | stop services'
  ansible.builtin.systemd:
    name: 'plexmediaserver.service'
    state: 'stopped'
  failed_when: false

- name: 'Backup | fetch | Preferences.xml'
  when: plex_flg_backup_config
  ansible.builtin.fetch:
    src: '{{ plex___app._cfg }}'
    dest: '{{
        plex__cfg._backup_dir ~ "/" ~ plex__cfg._start ~ "_Preferences.xml"
      }}'
    fail_on_missing: false
    flat: true

- name: 'Backup | fetch | databases'
  when: plex_flg_backup_db
  ansible.builtin.fetch:
    src: '{{ plex___app._db_dir ~ "/" ~ item }}'
    dest: '{{ plex__cfg._backup_dir ~ "/" ~ plex__cfg._start ~ "_" ~ item }}'
    fail_on_missing: false
    flat: true
  loop:
    - 'com.plexapp.plugins.library.blobs.db'
    - 'com.plexapp.plugins.library.blobs.db-shm'
    - 'com.plexapp.plugins.library.blobs.db-wal'
    - 'com.plexapp.plugins.library.db'
    - 'com.plexapp.plugins.library.db-shm'
    - 'com.plexapp.plugins.library.db-wal'

- name: 'Backup | systemd | start services'
  when: plex_flg_start
  ansible.builtin.systemd:
    name: 'plexmediaserver.service'
    state: 'started'
  failed_when: false

- name: 'Backup | success ✔'
  ansible.builtin.meta: 'end_host'
