---
###############################################################################
# Backup
###############################################################################

- name: 'Backup | systemd | stop plexmediaserver.service'
  ansible.builtin.systemd:
    name: 'plexmediaserver.service'
    state: 'stopped'
  failed_when: false

- name: 'Backup | filesystem | set backup location'
  when: plex__cfg._backup_dir | length > 0 and plex__cfg._backup_dir != '/tmp'
  delegate_to: 'localhost'
  run_once: true
  ansible.builtin.file:
    path: '{{ plex__cfg._backup_dir }}'
    mode: '0750'
    state: directory

- name: '{{ "Backup | fetch | " ~ plex___app._cfg }}'
  ansible.builtin.fetch:
    src: '{{ plex___app._cfg }}'
    dest: '{{
        plex__cfg._backup_dir ~ "/" ~ plex__srv._start ~ "_Preferences.xml"
      }}'
    fail_on_missing: false
    flat: true

- name: 'Backup | fetch | databases'
  ansible.builtin.fetch:
    src: '{{ plex___app._db_dir ~ "/" ~ item }}'
    dest: '{{ plex__cfg._backup_dir ~ "/" ~ plex__srv._start ~ "_" ~ item }}'
    fail_on_missing: false
    flat: true
  loop:
    - 'com.plexapp.plugins.library.blobs.db'
    - 'com.plexapp.plugins.library.blobs.db-shm'
    - 'com.plexapp.plugins.library.blobs.db-wal'
    - 'com.plexapp.plugins.library.db'
    - 'com.plexapp.plugins.library.db-shm'
    - 'com.plexapp.plugins.library.db-wal'

- name: 'Backup | start'
  ansible.builtin.import_tasks: 'start.yml'

- name: 'Backup | success ✔'
  ansible.builtin.meta: 'end_host'
