---
###############################################################################
# Configure Plex Install
###############################################################################
# Plex reads/re-writes only once at startup. Saving in the WebUI will write
# current running config to disk.
#
# Plex copies  existing values and generates the following if missing:
# * IPNetworkType
# * OldestPreviousVersion
# * MachineIdentifier
# * ProcessedMachineIdentifier
# * AnonymousMachineIdentifier

- name: '{{ "Config | filesystem | set " ~ plex___app._cfg }}'
  ansible.builtin.template:
    src: '{{ plex__cfg._preferences }}'
    dest: '{{ plex___app._cfg }}'
    owner: '{{ plex__cfg._uid }}'
    group: '{{ plex__cfg._gid }}'
    mode: '0600'
  become: true
  become_user: '{{ plex__srv._user }}'
