---
###############################################################################
# DB Repair
###############################################################################
# Manage DB repair script configuration. Deferrable.
#
# Reference:
# * https://github.com/ChuckPa/DBRepair

- name: 'DB repair | filesystem | set /etc/systemd/system/plex_repair.*'
  when: plex_flg_db_repair
  notify: 'Handlers | enable plex_repair'
  ansible.builtin.template:
    src: '{{ "systemd/" ~ item ~ ".j2" }}'
    dest: '{{ "/etc/systemd/system/" ~ item }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - 'plex_repair.service'
    - 'plex_repair.timer'

- name: 'DB repair | filesystem | remove /etc/systemd/system/plex_repair.*'
  when: not plex_flg_db_repair
  notify: 'Handlers | disable plex_repair'
  ansible.builtin.file:
    path: '{{ "/etc/systemd/system/" ~ item }}'
    state: 'absent'
  loop:
    - 'plex_repair.service'
    - 'plex_repair.timer'
