---
# yamllint disable rule:line-length
###############################################################################
# Plex Entitlements (PlexPass)
###############################################################################
# Check for entitlements (PlexPass) and install them if enabled.
#
# If plex_online_token is not entitled, the current version is returned.
#
# Download and install the entitlement package manually. Package will enable
# the same default APT repository as non-entitled plex installs.

- name: 'Entitlements | check installed packages'
  ansible.builtin.package_facts:  # requires ansible.posix

- name: 'Entitlements | query plexpass entitlements'
  ansible.builtin.uri:
    url: 'https://plex.tv/downloads/details/5?distro=debian&build=linux-{{ plex_service_arch_generic }}&channel=8&X-Plex-Token={{ plex_online_token }}'
    method: 'GET'
    return_content: true
  register: _plex_entitlement
  no_log: true  # lifetime API access token

- name: 'Entitlements | determine plexpass version'
  ansible.builtin.set_fact:
    _plex_pass_version: "{{ (_plex_entitlement.content | regex_findall('version=\"([\\w\\.-]+)\"'))[1] }}"

- name: 'Entitlements | determine installed version'
  ansible.builtin.set_fact:
    _plex_installed_version: '{{ ansible_facts.packages["plexmediaserver"][0].version }}'

# Entitlements must be manually installed.
- name: 'Entitlements | upgrade to plexpass version'
  when: _plex_installed_version != _plex_pass_version
  ansible.builtin.apt:
    deb: 'https://downloads.plex.tv/plex-media-server-new/{{ _plex_pass_version }}/debian/plexmediaserver_{{ _plex_pass_version }}_{{ plex_service_arch }}.deb'
  notify: 'Handlers | restart plex'
