---
###############################################################################
# Maintenance
###############################################################################
# Prune any old files from previous role versions. This is executed before any
# operations with the new role version.
#
# Use shell command to increase execution speed for multiple directories.

# 9.0.0 changed role structure:
# * Services moved to plex_*.
# * plexupdate, DBRepair moved to /etc/plex.
# * Pre 1.43.0.10467 installed plexmediaserver.service to wrong location.
- name: 'Maintenance | 9.0.0 | remove deprecated files'
  ansible.builtin.shell: >-
    rm -f /etc/systemd/system/plex-update.* &&
    rm -f /etc/systemd/system/plex-repair.* &&
    rm -f {{ plex___app._root_dir ~ "/plexupdate" }} &&
    rm -f /usr/bin/DBRepair.sh &&
    rm -f /etc/systemd/system/plexmediaserver.service &&
    rm -f /etc/apt/sources.list.d/plex.list &&
    rm -f /etc/apt/sources.list.d/plexmediaserver.list
  args:
    executable: '/bin/bash'
    removes: '/etc/systemd/system/plex-update.service'
