---
###############################################################################
# Manager Plex Users
###############################################################################
# Check if user exists and create if enabled.
#
# Args:
#   plex_user: string plex username.
#   plex_group: string plex group.
#   plex_create_user: boolean true to create role default user.
#   plex_default_user: dict containing builitin.user options for plex.
#   plex_default_group: dict containing builitin.group options for plex.

- name: 'manage users | confirm user exists'
  ansible.builtin.command: 'id {{ plex_user }}'
  register: _plex_user_exists
  changed_when: _plex_user_exists.rc > 0
  failed_when: false

- name: 'manage users | confirm group exists'
  ansible.builtin.command: 'groups {{ plex_group }}'
  register: _plex_group_exists
  changed_when: _plex_group_exists.rc > 0
  failed_when: false

- name: 'manage users | create plex group'
  ansible.builtin.group:
    name:  '{{ plex_default_group.name }}'
    gid:   '{{ plex_default_group.gid }}'
    state: 'present'
  when: plex_create_user and _plex_group_exists.rc != 0

- name: 'manage users | create plex user (logins disabled)'
  ansible.builtin.user:
    name:            '{{ plex_default_user.name }}'
    group:           '{{ plex_default_user.group }}'
    uid:             '{{ plex_default_user.uid }}'
    shell:           '{{ plex_default_user.shell }}'
    home:            '{{ plex_default_user.home }}'
    create_home:     '{{ plex_default_user.create_home }}'
    password:        '{{ plex_default_user.password }}'
    password_lock:   '{{ plex_default_user.password_lock }}'
    update_password: '{{ plex_default_user.update_password }}'
    expires:         '{{ plex_default_user.expires }}'
    system:          '{{ plex_default_user.system }}'
    state:           'present'
  when: plex_create_user and _plex_user_exists.rc != 0
