---
# yamllint disable rule:line-length
###############################################################################
# Plex Update
###############################################################################
# Install plex update cron to keep plex up to latest plex-pass version.
#
# Args:
#   _plex_uid: int - Plex user UID.
#   _plex_gid: int - Plex user GID.
#
# Reference:
# * https://github.com/mrworf/plexupdate
# * https://github.com/linuxserver/docker-plex/blob/master/root/etc/cont-init.d/60-plex-update
# yamllint enable rule:line-length

- name: 'Update | enable'
  when: plex_service_auto_update_enable
  block:
    - name: 'Update | enable | auto-update script'
      ansible.builtin.template:
        src: 'plexupdate.j2'
        dest: '{{ _plex_library_dir }}/plexupdate'
        owner: '{{ _plex_uid }}'
        group: '{{ _plex_gid }}'
        mode: '0750'

    - name: 'Update | enable | systemd'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.systemd'
      vars:
        systemd_services:
          - name: 'plex-update'
            state: 'present'
            drop_in: false
            unit:
              description: 'Automatically update Plex Media Server.'
              requires: ['plex-update.timer']
            service:
              type: 'oneshot'
              exec_start: ['"{{ _plex_library_dir }}/plexupdate"']
              success_exit_status: ['0', '1']
            exec:
              user: 'root'
              group: 'root'
            install:
              wanted_by: ['multi-user.target']
        systemd_timers:
          - name: 'plex-update'
            state: 'present'
            drop_in: false
            unit:
              description: 'plex-update.service timer'
              requires: ['plex-update.service']
            timer:
              unit: 'plex-update.service'
              on_calendar: ['*-*-* 04:00:00']
            install:
              wanted_by: ['timers.target']

- name: 'Update | disable'
  when: not plex_service_auto_update_enable
  block:
    - name: 'Update | disable | auto-update script'
      ansible.builtin.file:
        path: '{{ _plex_library_dir }}/plexupdate'
        state: 'absent'

    - name: 'Update | disable | systemd'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.systemd'
      vars:
        systemd_services:
          - name: 'plex-update'
            state: 'absent'
            drop_in: false
        systemd_timers:
          - name: 'plex-update'
            state: 'absent'
            drop_in: false
