---
# yamllint disable rule:line-length
collections:
  - 'ansible.posix'  # https://docs.ansible.com/ansible/latest/collections/ansible/posix/index.html
  - 'community.general'  # https://docs.ansible.com/ansible/latest/collections/ansible/posix/index.html
  - 'r_pufky.srv'  # https://github.com/r-pufky/ansible_collection_srv

roles: []
