---
- name: 'Prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Prepare | create manual managed user plex'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.users'
        tasks_from: 'role_account_add.yml'
      vars:
        users_role_group:
          name: 'plex'
          gid: 997
        users_role_user:
          name: 'plex'
          group: 'plex'
          uid: 997
          shell: '/usr/sbin/nologin'
          home: '/var/lib/plexmediaserver'
          create_home: false
          password: '!'
          password_lock: true
          update_password: 'always'
          expires: -1
          system: true
