---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | gather service status'
      ansible.builtin.service_facts:

    - name: >
        Default | verify |
        /etc/systemd/system/plexmediaserver.service.d/override.conf
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: >
          Default | verify |
          /etc/systemd/system/plexmediaserver.service.d/override.conf
        test_src: 'files/override.conf'
        test_file:
          '/etc/systemd/system/plexmediaserver.service.d/override.conf'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_diff: true

    - name: 'Verify | assert plex-update.service absent'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"plex-update.service" not in ansible_facts.services'
        fail_msg: '✘ plex-update.service should be removed.'

    - name: 'Verify | /etc/systemd/system/plex-update.timer'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name:
          'Verify | /etc/systemd/system/plex-update.timer'
        test_file: '/etc/systemd/system/plex-update.timer'
        test_owner: '{{ omit }}'
        test_group: '{{ omit }}'
        test_mode: '{{ omit }}'
        test_state: 'absent'
        test_diff: true

    - name: >
        Verify | /var
        /lib/plexmediaserver/Library/Application
        Support/Plex Media Server/plexupdate
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: >
          Verify | /var
          /lib/plexmediaserver/Library/Application
          Support/Plex Media Server/plexupdate
        test_file: '{{
            "/var/lib/plexmediaserver/Library/" ~
            "Application Support/" ~
            "Plex Media Server/" ~
            "plexupdate"
          }}'
        test_owner: '{{ omit }}'
        test_group: '{{ omit }}'
        test_mode: '{{ omit }}'
        test_state: 'absent'
        test_diff: true

    - name: 'Verify | query user plex'
      ansible.builtin.getent:
        database: 'passwd'
        key: 'plex'
      register: _test_plex_srv_user

    - name: 'Verify | assert user plex exists'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"plex" in ansible_facts.getent_passwd'
        fail_msg: '✘ plex user should exist {{ ansible_facts.getent_passwd }}.'

    - name: 'Verify | query current plex configuration'
      community.general.xml:
        path: '{{
            "/var/lib/plexmediaserver/Library/" ~
            "Application Support/" ~
            "Plex Media Server/" ~
            "Preferences.xml"
          }}'
        content: 'attribute'
        xpath: '/Preferences'
      register: _plex_xml_raw

    - name: 'Verify | parse current plex configuration'
      ansible.builtin.set_fact:
        _plex_xml: '{{ _plex_xml_raw.matches[0].Preferences }}'

    - name: 'Verify | DB auto grow size'
      ansible.builtin.assert:
        quiet: true
        that:
          - _plex_xml.DatabaseCacheSize == '40'
        fail_msg: >
          ✘ DatabaseCacheSize should be exactly 40
          ({{ _plex_xml.DatabaseCacheSize }}).

    - name: 'Verify | auto-generated preference overwritten'
      ansible.builtin.assert:
        quiet: true
        that:
          - _plex_xml.HardwareDevicePath == '10de:1eb1:10de:12a0@0000:42:00.0'
        fail_msg: >
          ✘ HardwareDevicePath should have pre-configured value
          ({{ _plex_xml.HardwareDevicePath }}).
