---
###############################################################################
# Plex Handlers
###############################################################################

- name: 'Handlers | restart plex'
  ansible.builtin.systemd:
    name: 'plexmediaserver'
    enabled: true
    state: 'restarted'

- name: 'Handlers | reload plex'
  ansible.builtin.systemd:
    daemon_reload: true
