---
# yamllint disable rule:line-length
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | TESTING NOT ENABLED ⚠'
      when: plex_cfg_online_token is not defined
      ansible.builtin.debug:
        msg: |
          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │      TEST WILL NOT EXECUTE UNLESS IT IS EXPLICITLY ENABLED.       │
          │                                                                   │
          ├───────────────────────────────────────────────────────────────────╯
          │ Set plex_cfg_online_token with a PlexPass entitlement:
          │
          │   molecule test -s entitlement_test -- -v -e \
          │     'plex_cfg_online_token={TOKEN}'

    - name: 'Converge | apply r_pufky.srv.plex'
      when: plex_cfg_online_token is defined
      ansible.builtin.include_role:
        name: 'r_pufky.srv.plex'
