---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.srv.plex'
      when: plex_cfg_online_token is defined
      ansible.builtin.include_role:
        name: 'r_pufky.srv.plex'
