---
###############################################################################
# Entitlement Test
###############################################################################
# Use a real plex entitlement token with PlexPass to verify entitlement
# executes correctly.
#
#   molecule test -s entitlement_test -- -v -e 'plex_cfg_online_token={TOKEN}'
#
# Tests:
# * Validate use of a real entitlement key.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        repo_testing_enable: true
platforms:
  - name: 'plex-12-entitlement_test'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
    # published_ports:
    #   - '32400/tcp'
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'converge'
    - 'verify'
    - 'destroy'
