---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | assert role success'
      ansible.builtin.assert:
        quiet: true
        that:
          - 0 == 0
        fail_msg: |
          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │              Role should execute without any errors.              │
          │                                                                   │
          ╰───────────────────────────────────────────────────────────────────╯
