---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.media.plex'
      ansible.builtin.include_role:
        name: 'r_pufky.media.plex'

    - name: 'Converge | apply r_pufky.media.plex (backup)'
      ansible.builtin.include_role:
        name: 'r_pufky.media.plex'
      vars:
        plex_flg_backup_config: true
        plex_flg_backup_db: true
        plex_cfg_backup_dir: '/tmp/ansible_plex_test'
