---
###############################################################################
# Default
###############################################################################
# Default configuration is deployed successfully.
#
# Tests:
# * override, plex_update, plex_repair unit files correct format.
# * plex_update, plex_repair services are active (plexmediaserver verified by
#   role).
# * /opt/plex/{DBRepair.sh,plex_update} exist.
# * Backup files are copied to local controller.
# * Service is restarted after backup completion.
# * Preferences.xml with templated variables work.
# * Role finishes successfully without additional tasks.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        url_inject_enable: true
        plex_flg_preferences: true
        test_variable: 'TEST'
        plex_cfg_preferences: '{{
            lookup("env", "MOLECULE_SCENARIO_DIRECTORY") ~
            "/files/Preferences.xml"
          }}'
platforms:
  - name: 'plex_default'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'verify'
    - 'destroy'
