---
- name: 'Prepare'
  hosts: 'localhost'
  gather_facts: false
  tasks:
    - name: 'Prepare | import | role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: '{{ "Prepare | cache " ~ plex___repair._package }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: '{{ "Prepare | cache " ~ plex___repair._package }}'
        test_dest: '{{ plex___repair._package }}'
        test_url: '{{ plex___repair._url }}'
        test_mode: '0640'

- name: 'Prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Prepare | import | role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: 'Prepare | inject | cached packages'
      when: (url_inject_enable | default(false))
      ansible.builtin.copy:
        src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/molecule/cache/" ~
            plex___repair._package
          }}'
        dest: '{{ "/tmp/" ~ plex___repair._package }}'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: 'Prepare | inject | required testing packages'
      ansible.builtin.apt:
        name: 'python3-lxml'
        state: 'present'
