---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: 'Verify | systemd units'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name:
          '{{ "Verify | systemd units | /etc/systemd/system/" ~ item }}'
        test_src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/files/" ~ item
          }}'
        test_file: '{{ "/etc/systemd/system/" ~ item }}'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_diff: true
      loop:
        - 'plexmediaserver.service.d/override.conf'
        - 'plex_update.service'
        - 'plex_update.timer'
        - 'plex_repair.service'
        - 'plex_repair.timer'

    - name: 'Verify | /opt/plex'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: '{{ "Verify | /opt/plex/" ~ item }}'
        test_file: '{{ "/opt/plex/" ~ item }}'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0755'
        test_state: 'file'
        test_diff: true
      loop:
        - 'plex_update'
        - 'DBRepair.sh'

    - name: 'Verify | query Preferences.xml'
      community.general.xml:
        path: '{{ plex___app._cfg }}'
        content: 'attribute'
        xpath: '/Preferences'
      register: plex__test

    - name: 'Verify | parse Preferences.xml'
      ansible.builtin.set_fact:
        _test_plex_xml: '{{ plex__test.matches[0].Preferences }}'

    - name: 'Verify | assert Preferences.xml TestVariable'
      ansible.builtin.assert:
        quiet: true
        that:
          - _test_plex_xml.TestVariable == 'TEST'
        fail_msg: |

          ✘ TestVariable should be 'TEST'.
          TestVariable: {{ _test_plex_xml.TestVariable }}
