---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: 'Verify | test | systemd units'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'copy.yml'
      vars:
        test_name:
          '{{ "Verify | test | /etc/systemd/system/" ~ item }}'
        test_src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/files/" ~ item
          }}'
        test_file: '{{ "/etc/systemd/system/" ~ item }}'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_diff: true
      loop:
        - 'plexmediaserver.service.d/override.conf'
        - 'plex_update.service'
        - 'plex_update.timer'
        - 'plex_repair.service'
        - 'plex_repair.timer'

    - name: '{{ "Verify | test | " ~ plex___app._opt_dir }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'file.yml'
      vars:
        test_name:
          '{{ "Verify | test | " ~ plex___app._opt_dir ~ "/" ~ item }}'
        test_file: '{{ plex___app._opt_dir ~ "/" ~ item }}'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0755'
        test_state: 'file'
        test_diff: true
      loop:
        - '{{ plex___update._package }}'
        - '{{ plex___repair._package }}'

    - name: '{{ "Verify | xml | query " ~ plex___app._cfg }}'
      community.general.xml:
        path: '{{ plex___app._cfg }}'
        content: 'attribute'
        xpath: '/Preferences'
      register: plex__test

    - name: 'Verify | fact | parse Preferences.xml'
      ansible.builtin.set_fact:
        plex__test_xml: '{{ plex__test.matches[0].Preferences }}'

    - name: 'Verify | assert | Preferences.xml TestVariable set'
      ansible.builtin.assert:
        quiet: true
        that:
          - plex__test_xml.TestVariable == 'TEST'
        fail_msg: |

          ✘ TestVariable should be 'TEST'.
          TestVariable: {{ plex__test_xml.TestVariable }}
