---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | systemd units'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name:
          '{{ "Verify | systemd units | /etc/systemd/system/" ~ item }}'
        test_src: '{{ "files/" ~ item }}'
        test_file: '{{ "/etc/systemd/system/" ~ item }}'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_diff: true
      loop:
        - 'plexmediaserver.service.d/override.conf'
        - 'plex_update.service'
        - 'plex_update.timer'
        - 'plex_repair.service'
        - 'plex_repair.timer'

    - name: 'Verify | gather plex_update.timer status'
      ansible.builtin.command: 'systemctl status plex_update.timer'
      register: _test_plex_timer_status
      changed_when: false

    - name: 'Verify | assert plex_update.timer active'
      ansible.builtin.assert:
        quiet: true
        that:
          - _test_plex_timer_status.rc == 0
          - '"Active: active" in _test_plex_timer_status.stdout'
        fail_msg: |

          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │               plex_update.timer should be enabled.                │
          │                                                                   │
          ╰───────────────────────────────────────────────────────────────────╯

    - name: 'Verify | gather plex_repair.timer status'
      ansible.builtin.command: 'systemctl status plex_repair.timer'
      register: _test_plex_timer_status
      changed_when: false

    - name: 'Verify | assert plex_repair.timer active'
      ansible.builtin.assert:
        quiet: true
        that:
          - _test_plex_timer_status.rc == 0
          - '"Active: active" in _test_plex_timer_status.stdout'
        fail_msg: |

          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │               plex_repair.timer should be enabled.                │
          │                                                                   │
          ╰───────────────────────────────────────────────────────────────────╯

    - name: 'Verify | /opt/plex'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: '{{ "Verify | /opt/plex/" ~ item }}'
        test_file: '{{ "/opt/plex/" ~ item }}'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0755'
        test_state: 'file'
        test_diff: true
      loop:
        - 'plex_update'
        - 'DBRepair.sh'

    - name: 'Verify | query Preferences.xml'
      community.general.xml:
        path: '{{
            "/var/lib/plexmediaserver/Library/Application Support/" ~
            "Plex Media Server/Preferences.xml"
          }}'
        content: 'attribute'
        xpath: '/Preferences'
      register: _test_plex_xml_raw

    - name: 'Verify | parse Preferences.xml'
      ansible.builtin.set_fact:
        _test_plex_xml: '{{ _test_plex_xml_raw.matches[0].Preferences }}'

    - name: 'Verify | assert Preferences.xml TestVariable'
      ansible.builtin.assert:
        quiet: true
        that:
          - _test_plex_xml.TestVariable == 'TEST'
        fail_msg: |

          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │                  TestVariable should be 'TEST'.                   │
          │                                                                   │
          ├───────────────────────────────────────────────────────────────────╯
          │ {{ _test_plex_xml.TestVariable }}

- name: 'Verify'
  hosts: 'localhost'
  gather_facts: false
  tasks:
    - name: 'Verify | query backup Preferences.xml'
      ansible.builtin.find:
        path: '/tmp/ansible_plex_test'
        patterns: '*_Preferences.xml'
      register: _test_plex_backup_preferences

    - name: 'Verify | assert backup Preferences.xml'
      ansible.builtin.assert:
        quiet: true
        that:
          - _test_plex_backup_preferences.matched >= 1
        fail_msg: |

          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │                  Preferences.xml not backed up.                   │
          │                                                                   │
          ╰───────────────────────────────────────────────────────────────────╯

    - name: 'Verify | query backup com.plexapp.plugins.library.db'
      ansible.builtin.find:
        path: '/tmp/ansible_plex_test'
        patterns: '*_com.plexapp.plugins.library.db'
        file_type: 'file'
      register: _test_plex_backup_db

    - name: 'Verify | assert backup com.plexapp.plugins.library.db'
      ansible.builtin.assert:
        quiet: true
        that:
          - _test_plex_backup_db.matched >= 1
        fail_msg: |

          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │          com.plexapp.plugins.library.db* not backed up.           │
          │                                                                   │
          ╰───────────────────────────────────────────────────────────────────╯

    - name: 'Verify | query backup com.plexapp.plugins.library.blobs'
      ansible.builtin.find:
        path: '/tmp/ansible_plex_test'
        patterns: '*_com.plexapp.plugins.library.blobs.db'
        file_type: 'file'
      register: _test_plex_backup_blob

    - name: 'Verify | assert backup com.plexapp.plugins.library.blobs'
      ansible.builtin.assert:
        quiet: true
        that:
          - _test_plex_backup_blob.matched >= 1
        fail_msg: |

          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │        com.plexapp.plugins.library.blobs.* not backed up.         │
          │                                                                   │
          ╰───────────────────────────────────────────────────────────────────╯
