---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: >
        Default | verify |
        /etc/systemd/system/plexmediaserver.service.d/override.conf
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: >
          Default | verify |
          /etc/systemd/system/plexmediaserver.service.d/override.conf
        test_src: 'files/override.conf'
        test_file:
          '/etc/systemd/system/plexmediaserver.service.d/override.conf'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_diff: true

    - name: 'Verify | gather plex-update.timer status'
      ansible.builtin.command: 'systemctl status plex-update.timer'
      register: _test_plex_timer_status
      changed_when: false

    - name: 'Verify | assert plex-update.timer active'
      ansible.builtin.assert:
        quiet: true
        that:
          - _test_plex_timer_status.rc == 0
          - '"Active: active" in _test_plex_timer_status.stdout'
        fail_msg: |
          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │               plex-update.timer should be enabled.                │
          │                                                                   │
          ╰───────────────────────────────────────────────────────────────────╯

    - name: 'Verify | /etc/systemd/system/plex-update.timer'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | /etc/systemd/system/plex-update.timer'
        test_src: 'files/plex-update.timer'
        test_file: '/etc/systemd/system/plex-update.timer'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_diff: true

    - name: 'Verify | query current plex configuration'
      community.general.xml:
        path: '{{
            "/var/lib/plexmediaserver/Library/" ~
            "Application Support/" ~
            "Plex Media Server/" ~
            "Preferences.xml"
          }}'
        content: 'attribute'
        xpath: '/Preferences'
      register: _plex_xml_raw

    - name: 'Verify | parse current plex configuration'
      ansible.builtin.set_fact:
        _plex_xml: '{{ _plex_xml_raw.matches[0].Preferences }}'

    - name: 'Verify | DB auto grow size'
      ansible.builtin.assert:
        quiet: true
        that:
          - _plex_xml.DatabaseCacheSize == '44'
        fail_msg: |
          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │               DatabaseCacheSize should grow to 44.                │
          │                                                                   │
          ├───────────────────────────────────────────────────────────────────╯
          │ {{ _plex_xml.DatabaseCacheSize }}

    - name: 'Verify | auto-generated preference passed through'
      ansible.builtin.assert:
        quiet: true
        that:
          - _plex_xml.MachineIdentifier != ''
        fail_msg: |
          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │      MachineIdentifier should have an auto-generated value.       │
          │                                                                   │
          ╰───────────────────────────────────────────────────────────────────╯

    # Stateful will override the user configured value.
    - name: 'Verify | stateful preference passed through'
      ansible.builtin.assert:
        quiet: true
        that:
          - _plex_xml.AcceptedEULA == '1'
        fail_msg: |
          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │           AcceptedEULA should be a stateful value (1).            │
          │                                                                   │
          ├───────────────────────────────────────────────────────────────────╯
          │ {{ _plex_xml.AcceptedEULA }}

    # Experimental options are not rendered by default.
    - name: 'Verify | stateful preference passed through'
      ansible.builtin.assert:
        quiet: true
        that:
          - _plex_xml.GenerateBIFFrameInterval is not defined
        fail_msg: |
          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │            GenerateBIFFrameInterval should not exist.             │
          │                                                                   │
          ╰───────────────────────────────────────────────────────────────────╯
