---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | query current plex configuration'
      community.general.xml:
        path: '{{
            "/var/lib/plexmediaserver/Library/" ~
            "Application Support/" ~
            "Plex Media Server/" ~
            "Preferences.xml"
          }}'
        content: 'attribute'
        xpath: '/Preferences'
      register: _plex_xml_raw

    - name: 'Verify | parse current plex configuration'
      ansible.builtin.set_fact:
        _plex_xml: '{{ _plex_xml_raw.matches[0].Preferences }}'

    - name: 'Verify | GenerateBIFFrameInterval'
      ansible.builtin.assert:
        quiet: true
        that:
          - _plex_xml.GenerateBIFFrameInterval == '15'
        fail_msg: |
          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │              GenerateBIFFrameInterval should be 15.               │
          │                                                                   │
          ├───────────────────────────────────────────────────────────────────╯
          │ {{ _plex_xml.GenerateBIFFrameInterval }}
