---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: 'Verify | query Preferences.xml'
      community.general.xml:
        path: '{{ plex___app._cfg }}'
        content: 'attribute'
        xpath: '/Preferences'
      register: plex__test

    - name: 'Verify | parse Preferences.xml'
      ansible.builtin.set_fact:
        _test_plex_xml: '{{ plex__test.matches[0].Preferences }}'

    - name: 'Verify | assert Preferences.xml TestVariable'
      ansible.builtin.assert:
        quiet: true
        that:
          - _test_plex_xml.TestVariable == 'TEST'
        fail_msg: |

          ✘ TestVariable should be 'TEST'.
          TestVariable: {{ _test_plex_xml.TestVariable }}

    - name: '{{ "Verify | " ~ plex___app._db_dir ~ "*.db" }}'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: '{{ plex_cfg_backup_dir ~ "/" ~ item }}'
        test_file: '{{ plex___app._db_dir ~ "/" ~ item }}'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0644'
        test_state: 'file'
        test_diff: true
      loop:
        - 'com.plexapp.plugins.library.blobs.db'
        - 'com.plexapp.plugins.library.db'
